default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: nikhil
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: office_token_bootstrap_app_development

test:
  <<: *default
  database: office_token_bootstrap_app_test

production:
  <<: *default
  database: office_token_bootstrap_app_production
  username: office_token_bootstrap_app
  password: <%= ENV["OFFICE_TOKEN_BOOTSTRAP_APP_DATABASE_PASSWORD"] %>
